---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
  namespace: washere
  labels:
    app: washere
    component: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: washere
      component: frontend 
  template:
    metadata:
      labels:
        app: washere
        component: frontend 
    spec:
      containers:
      - name: main
        image: cjhouser/washere:frontend
        imagePullPolicy: Always
        command:
        - "/work/run"
        env:
        - name: LISTEN_SOCKET
          value: 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: washere 
spec:
  ports:
  - port: 8080
    nodePort: 32222
  selector:
    app: washere
    component: frontend
  type: NodePort
---