---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader 
  namespace: washere
  labels:
    app: washere
    component: reader
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: washere
      component: reader 
  template:
    metadata:
      labels:
        app: washere
        component: reader 
    spec:
      containers:
      - name: main
        image: cjhouser/washere:reader
        imagePullPolicy: Always
        command:
        - "/work/run"
        env:
        - name: DATABASE_URL
          value: postgres://postgres:development@database:5432/washere
        - name: LISTEN_SOCKET
          value: 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: reader
  namespace: washere 
spec:
  ports:
  - port: 8080
  selector:
    app: washere
    component: reader
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reader
  namespace: washere
spec:
  ingressClassName: nginx
  rules:
  - host: washere.com
    http:
      paths:
      - backend:
          service:
            name: reader
            port:
              number: 8080
        path: /signatures
        pathType: Exact
---
