---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creator 
  namespace: washere
  labels:
    app: washere
    component: creator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: washere
      component: creator 
  template:
    metadata:
      labels:
        app: washere
        component: creator 
    spec:
      containers:
      - name: main
        image: cjhouser/washere:creator
        imagePullPolicy: Always
        command:
        - "/work/run"
        env:
        - name: LISTEN_SOCKET
          value: 0.0.0.0:8080
        - name: NSQD_SOCKET
          value: nsqd.default:4150
        envFrom:
        - secretRef:
            name: new-relic-license
        resources:
          limits:
            memory: 8Mi
          requests:
            cpu: 8m 
---
apiVersion: v1
kind: Secret
metadata:
  name: new-relic-license
  namespace: washere
stringData:
  NEW_RELIC_LICENSE: 
---
apiVersion: v1
kind: Service
metadata:
  name: creator
  namespace: washere 
spec:
  ports:
  - port: 8080
  selector:
    app: washere
    component: creator
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creator
  namespace: washere
spec:
  ingressClassName: nginx
  rules:
  - host: washere.com
    http:
      paths:
      - backend:
          service:
            name: creator
            port:
              number: 8080
        path: /signatures/create
        pathType: Exact
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: creator 
  namespace: washere
spec:
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creator
---