---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creator 
  namespace: washere
  labels:
    app: washere
    component: creator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: washere
      component: creator 
  template:
    metadata:
      labels:
        app: washere
        component: creator 
    spec:
      containers:
      - name: main
        image: cjhouser/washere:creator
        imagePullPolicy: Always
        command:
        - "/work/run"
        env:
        - name: LISTEN_SOCKET
          value: 0.0.0.0:8080
        - name: NSQD_SOCKET
          value: nsqd.default:4150
---
apiVersion: v1
kind: Service
metadata:
  name: creator
  namespace: washere 
spec:
  ports:
  - port: 8080
  selector:
    app: washere
    component: creator
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creator
  namespace: washere
spec:
  ingressClassName: nginx
  rules:
  - host: washere.com
    http:
      paths:
      - backend:
          service:
            name: creator
            port:
              number: 8080
        path: /signatures/create
        pathType: Exact
---