---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creator 
  namespace: washere
  labels:
    app: washere
    component: creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: washere
      component: creator 
  template:
    metadata:
      labels:
        app: washere
        component: creator 
    spec:
      containers:
      - name: main
        image: cjhouser/washere:creator
        imagePullPolicy: Always
        command:
        - "/work/run"
---
apiVersion: v1
kind: Service
metadata:
  name: creator
  namespace: washere 
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32005
  selector:
    app: washere
    component: creator
  type: NodePort
---